version: '3.9'

services:
  db:
    image: postgres:13
    container_name: octoquiz-db
    restart: always
    environment:
      POSTGRES_DB: octoquiz
      POSTGRES_USER: octoquizuser
      POSTGRES_PASSWORD: octopass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    network_mode: bridge

  web:
    build: .
    container_name: octoquiz-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - POSTGRES_DB=octoquiz
      - POSTGRES_USER=octoquizuser
      - POSTGRES_PASSWORD=octopass
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

volumes:
  postgres_data:
