# Generated by Django 5.0.4 on 2025-06-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='flashcard_photos/'),
        ),
    ]
